This is a practice to learn numpy. The original webset is https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
#q1
import numpy as np
print(np.__version__)

1.14.0


In [2]:
#q2
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#q3
np.full((3,3),True,dtype=np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
#q4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [5]:
#q5
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
#q6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = np.where(arr % 2 == 1,-1,arr)
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
#7
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])
np.concatenate([a,b],axis=0)
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
#9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])
np.concatenate([a,b],axis=1)
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
#10
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
#11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [12]:
#12
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [13]:
#13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[np.where(a==b)]
a[a==b]

array([2, 2, 4, 4])

In [14]:
#14
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where((a>=5) & (a<=10))]
a[np.where(np.logical_and(a>=5 , a<=10))]
a[(a >= 5) & (a <= 10)]


array([ 6,  9, 10])

In [15]:
#15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

np.array([maxx(x,y) for (x,y) in zip(a,b)])

maxx_vec = np.vectorize(maxx)
maxx_vec(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [16]:
#16
arr = np.arange(9).reshape(3,3)
print(arr)
#arr[:,[0,2]]=arr[:,[2,0]]
arr[:,[2,1,0]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [17]:
#17
arr = np.arange(9).reshape(3,3)
print(arr)
#arr[[0,2],:]=arr[[2,0],:]
arr[[2,1,0],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [18]:
#18
arr = np.arange(9).reshape(3,3)
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [19]:
#19
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [20]:
#20
arr = np.random.uniform(5,10,size=(3,3))
arr

array([[6.91752903, 7.35043235, 8.19020019],
       [5.41908989, 5.78194764, 7.3196855 ],
       [6.16087136, 9.40039205, 7.51788976]])

In [21]:
np.set_printoptions(precision=3)
print(arr)

[[6.918 7.35  8.19 ]
 [5.419 5.782 7.32 ]
 [6.161 9.4   7.518]]


In [22]:
help(np.set_printoptions)

Help on function set_printoptions in module numpy.core.arrayprint:

set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, **kwarg)
    Set printing options.
    
    These options determine the way floating point numbers, arrays and
    other NumPy objects are displayed.
    
    Parameters
    ----------
    precision : int, optional
        Number of digits of precision for floating point output (default 8).
    threshold : int, optional
        Total number of array elements which trigger summarization
        rather than full repr (default 1000).
    edgeitems : int, optional
        Number of array items in summary at beginning and end of
        each dimension (default 3).
    linewidth : int, optional
        The number of characters per line for the purpose of inserting
        line breaks (default 75).
    suppress : bool, optional
        If True, always print floati

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [24]:
species=[t.decode("utf-8") for t in iris[:,4]]

In [25]:
temp = iris[:,:4]
s1=temp.shape
temp.reshape((np.prod(s1),-1))

s=np.array([list(map(np.float,r)) for r in temp])

In [26]:
s.shape

(150, 4)

In [27]:
def f(x):
    return(x+5)
t=np.random.randint(low=0,high=10,size=(6,))


In [28]:
map(f,t)

In [29]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
iris_tag = np.genfromtxt(url, delimiter=',', dtype='str',usecols=[4])

In [30]:
iris.mean()
iris.mean(axis=0)
iris.mean(axis=1)
np.median(iris,axis=0)
np.std(iris)
iris.std()


1.974000985027335

In [31]:
sepallength=iris[:,0]
#sepallength=(sepallength-sepallength.min())/(sepallength.max()-sepallength.min())

In [32]:
help(sepallength.ptp)

Help on built-in function ptp:

ptp(...) method of numpy.ndarray instance
    a.ptp(axis=None, out=None)
    
    Peak to peak (maximum - minimum) value along a given axis.
    
    Refer to `numpy.ptp` for full documentation.
    
    See Also
    --------
    numpy.ptp : equivalent function



In [33]:
def soft_max_score(z):
    t=np.exp(z)
    return(t/t.sum)
def soft_max_score2(z):
    t=np.exp(z-z.max())
    return(t/t.sum())
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [34]:
soft_max_score2(sepallength)

array([0.002, 0.002, 0.001, 0.001, 0.002, 0.003, 0.001, 0.002, 0.001,
       0.002, 0.003, 0.002, 0.002, 0.001, 0.004, 0.004, 0.003, 0.002,
       0.004, 0.002, 0.003, 0.002, 0.001, 0.002, 0.002, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.002, 0.003, 0.002, 0.003, 0.002, 0.002,
       0.003, 0.002, 0.001, 0.002, 0.002, 0.001, 0.001, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.003, 0.002, 0.015, 0.008, 0.013, 0.003,
       0.009, 0.004, 0.007, 0.002, 0.01 , 0.002, 0.002, 0.005, 0.005,
       0.006, 0.004, 0.011, 0.004, 0.004, 0.007, 0.004, 0.005, 0.006,
       0.007, 0.006, 0.008, 0.01 , 0.012, 0.011, 0.005, 0.004, 0.003,
       0.003, 0.004, 0.005, 0.003, 0.005, 0.011, 0.007, 0.004, 0.003,
       0.003, 0.006, 0.004, 0.002, 0.004, 0.004, 0.004, 0.007, 0.002,
       0.004, 0.007, 0.004, 0.016, 0.007, 0.009, 0.027, 0.002, 0.02 ,
       0.011, 0.018, 0.009, 0.008, 0.012, 0.004, 0.004, 0.008, 0.009,
       0.03 , 0.03 , 0.005, 0.013, 0.004, 0.03 , 0.007, 0.011, 0.018,
       0.007, 0.006,

In [35]:
np.corrcoef(iris.T)

array([[ 1.   , -0.109,  0.872,  0.818],
       [-0.109,  1.   , -0.421, -0.357],
       [ 0.872, -0.421,  1.   ,  0.963],
       [ 0.818, -0.357,  0.963,  1.   ]])

In [36]:
import pandas as pd


In [37]:
pd.value_counts(species)

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
dtype: int64

In [38]:
tag=pd.Series(np.random.randint(3,size=(150,)))
D=pd.DataFrame({'species':species,'tag':tag})

In [39]:
pd.crosstab(np.ones((150,)),columns=[species,])


col_0  Iris-setosa  Iris-versicolor  Iris-virginica
row_0                                              
1.0             50               50              50

In [40]:
help(pd.crosstab)

Help on function crosstab in module pandas.tools.pivot:

crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, dropna=True, normalize=False)
    Compute a simple cross-tabulation of two (or more) factors. By default
    computes a frequency table of the factors unless an array of values and an
    aggregation function are passed
    
    Parameters
    ----------
    index : array-like, Series, or list of arrays/Series
        Values to group by in the rows
    columns : array-like, Series, or list of arrays/Series
        Values to group by in the columns
    values : array-like, optional
        Array of values to aggregate according to the factors.
        Requires `aggfunc` be specified.
    aggfunc : function, optional
        If specified, requires `values` be specified as well
    rownames : sequence, default None
        If passed, must match number of row arrays passed
    colnames : sequence, default None
        If passed, must matc

In [41]:
x = np.array(["large" for i in range(150)],dtype='<U10')
x[iris[:,2]<3]='small'
x[(iris[:,2]>=3)&(iris[:,2]<5)]='medium'
#x[iris[:,2]>=5]="large"
x



array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium

In [42]:
def get_tag(v):
    if v<3.5:
        return("small")
    elif v<5:
        return("medium")
    else:
        return("large")
v_get_tag = np.vectorize(get_tag);
s=v_get_tag(iris[:,2])
s

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'small', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'small', 'medium',

In [43]:
help(np.digitize)

Help on built-in function digitize in module numpy.core.multiarray:

digitize(...)
    digitize(x, bins, right=False)
    
    Return the indices of the bins to which each value in input array belongs.
    
    Each index ``i`` returned is such that ``bins[i-1] <= x < bins[i]`` if
    `bins` is monotonically increasing, or ``bins[i-1] > x >= bins[i]`` if
    `bins` is monotonically decreasing. If values in `x` are beyond the
    bounds of `bins`, 0 or ``len(bins)`` is returned as appropriate. If right
    is True, then the right bin is closed so that the index ``i`` is such
    that ``bins[i-1] < x <= bins[i]`` or ``bins[i-1] >= x > bins[i]`` if `bins`
    is monotonically increasing or decreasing, respectively.
    
    Parameters
    ----------
    x : array_like
        Input array to be binned. Prior to NumPy 1.10.0, this array had to
        be 1-dimensional, but can now have any shape.
    bins : array_like
        Array of bins. It has to be 1-dimensional and monotonic.
    righ

In [44]:
t=np.array(["sss" for i in range(1)],dtype='<U10')
t[0]="ssss"
t

array(['ssss'], dtype='<U10')

In [46]:
#45
petallength=iris[:,2]
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)],counts,vals)

1.5 [ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1] [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.9 3.  3.3 3.5 3.6 3.7 3.8 3.9 4.  4.1
 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9
 6.  6.1 6.3 6.4 6.6 6.7 6.9]
